apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  labels:
    {{- include "store-medusa.postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize | quote }}
