{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "store-platform.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    # Dashboard
    - host: {{ .Values.ingress.dashboardHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard
                port:
                  number: {{ .Values.dashboard.port }}
    # Intent API
    - host: {{ .Values.ingress.apiHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: intent-api
                port:
                  number: {{ .Values.api.port }}
{{- end }}
