apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront
  labels:
    {{- include "store-medusa.storefront.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.storefront.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: storefront
      app.kubernetes.io/instance: {{ .Values.storeName }}-sf
  template:
    metadata:
      labels:
        {{- include "store-medusa.storefront.labels" . | nindent 8 }}
    spec:
      containers:
        - name: storefront
          image: {{ .Values.storefront.image | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.storefront.port }}
              name: http
              protocol: TCP
          env:
            - name: MEDUSA_BACKEND_URL
              value: "medusa-backend:9000"
          resources:
            {{- toYaml .Values.storefront.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
